# Generated by Django 5.1.4 on 2026-05-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='01', max_length=30, verbose_name='sur-titre')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(default='fas fa-sparkles', max_length=60, verbose_name='icône')),
                ('theme', models.CharField(choices=[('burnt', 'Orange'), ('teal', 'Teal'), ('light', 'Light')], default='burnt', max_length=20, verbose_name='thème')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'slide hero',
                'verbose_name_plural': 'slides hero',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Omar Atta', max_length=120, verbose_name='nom complet')),
                ('brand_name', models.CharField(default='Omar.dev', max_length=120, verbose_name='nom de marque')),
                ('hero_badge_text', models.CharField(default='Disponible pour missions', max_length=120, verbose_name='badge hero')),
                ('hero_role', models.CharField(default='Ingénieur Freelance', max_length=120, verbose_name='rôle hero')),
                ('hero_highlight', models.CharField(default='IA, Logiciel, Mobile & Cloud AWS', max_length=180, verbose_name='mise en avant hero')),
                ('hero_description', models.TextField(default='Je conçois et mets en production des produits IA, applications métier, stacks cloud AWS et assistants virtuels pour startups, PME et équipes qui veulent livrer plus vite, mieux servir leurs clients et structurer leur croissance en Afrique et à l’international.', verbose_name='description hero')),
                ('years_experience', models.PositiveSmallIntegerField(default=4, verbose_name='années d’expérience')),
                ('experience_label', models.CharField(default="Ans d'expérience", max_length=120, verbose_name='libellé expérience')),
                ('impact_value', models.CharField(default='B2B', max_length=40, verbose_name='valeur impact')),
                ('impact_label', models.CharField(default='Approche orientée impact', max_length=120, verbose_name='libellé impact')),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='photo de profil')),
                ('about_photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='photo à propos')),
                ('about_title', models.CharField(default='Ingénieur orienté business, livraison rapide et impact mesurable.', max_length=180, verbose_name='titre à propos')),
                ('about_intro', models.TextField(default='Développeur full-stack spécialisé en IA, logiciels métier, applications mobiles, cloud AWS et automatisation, je transforme des besoins complexes en produits fiables, scalables et orientés retour sur investissement. Certifié IBM, j’interviens comme partenaire technique pour des entreprises en Afrique francophone, Europe et remote international.', verbose_name='introduction à propos')),
                ('about_body', models.TextField(default='Mon approche est simple : comprendre le problème métier, sécuriser l’architecture, livrer vite et mesurer l’impact. J’accompagne aussi bien des lancements MVP que des plateformes critiques, assistants virtuels et systèmes intelligents connectés au cloud.', verbose_name='texte à propos')),
                ('cv_file', models.FileField(blank=True, upload_to='profile/', verbose_name='CV')),
                ('footer_tagline', models.CharField(default='Ingénieur Freelance IA & Logiciel', max_length=160, verbose_name='sous-titre footer')),
                ('availability_text', models.CharField(default='Disponible pour nouvelles missions — Afrique & Remote', max_length=180, verbose_name='texte de disponibilité')),
                ('email', models.EmailField(default='attaomar66@gmail.com', max_length=254, verbose_name='email')),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/393287210929', verbose_name='URL WhatsApp')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/omaratta-805a36344', verbose_name='URL LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='URL GitHub')),
                ('hero_signals', models.CharField(default='IA,Mobile,AWS,Agents,Data,Automation', help_text='Valeurs séparées par virgule.', max_length=255, verbose_name='signaux hero')),
                ('tech_stack_marquee', models.CharField(default='Python,Django,React,Flutter,LangChain,RAG,Docker,AWS,Node.js,PostgreSQL,TensorFlow,n8n', help_text='Technologies séparées par virgule.', max_length=500, verbose_name='bande technologies')),
                ('primary_badge_text', models.CharField(default='IBM Certified', max_length=120, verbose_name='badge principal')),
                ('secondary_badge_text', models.CharField(default='Livraison orientée impact', max_length=120, verbose_name='badge secondaire')),
                ('secondary_badge_icon', models.CharField(default='fas fa-layer-group', max_length=60, verbose_name='icône badge secondaire')),
                ('primary_certificate_label', models.CharField(default='IBM AI Engineering', max_length=120, verbose_name='libellé certification 1')),
                ('primary_certificate_url', models.URLField(blank=True, default='https://www.credly.com/badges/84bc6f03-87d3-4fc6-b3dd-c67a48f70d2a/public_url', verbose_name='URL certification 1')),
                ('secondary_certificate_label', models.CharField(default='IBM Applied AI', max_length=120, verbose_name='libellé certification 2')),
                ('secondary_certificate_url', models.URLField(blank=True, default='https://www.credly.com/badges/b5b05f89-e8e7-48a4-b96d-f73b05b33f1f/public_url', verbose_name='URL certification 2')),
            ],
            options={
                'verbose_name': 'profil du site',
                'verbose_name_plural': 'profil du site',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'message de contact', 'verbose_name_plural': 'messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['order'], 'verbose_name': 'indicateur', 'verbose_name_plural': 'indicateurs'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'projet', 'verbose_name_plural': 'projets'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'compétence', 'verbose_name_plural': 'compétences'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-submitted_at'], 'verbose_name': 'témoignage', 'verbose_name_plural': 'témoignages'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order'], 'verbose_name': 'outil', 'verbose_name_plural': 'outils'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, max_length=50, verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='lu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='reçu le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='label',
            field=models.CharField(max_length=150, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='value',
            field=models.CharField(help_text='ex: +32%', max_length=30, verbose_name='valeur'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ia', 'IA & chatbot'), ('web', 'Web & e-commerce'), ('mobile', 'Application Mobile'), ('automation', 'Automatisation'), ('erp', 'ERP / CRM')], default='web', max_length=20, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, help_text='Problème client résolu', verbose_name='problème'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_video_file',
            field=models.FileField(blank=True, help_text='Vidéo démo uploadée directement (mp4)', upload_to='projects/videos/', verbose_name='fichier vidéo de démo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='URL YouTube/Vimeo embed ex: https://www.youtube.com/embed/XXXX', verbose_name='URL de démo vidéo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(verbose_name='description complète'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Lien GitHub du projet', verbose_name='URL GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Afficher en avant dans le portfolio', verbose_name='mis en avant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Lien vers le projet en ligne', verbose_name='URL live'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, help_text='Résultat mesurable ex: +32% conversion', verbose_name='résultat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='description courte'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='Solution apportée', verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(help_text='Tags séparés par virgule ex: Python,Django,IA', max_length=300, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/thumbnails/', verbose_name='miniature'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Classe Font Awesome ex: fas fa-brain', max_length=60, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('ia', 'IA & science des données'), ('web', 'Web & e-commerce'), ('mobile', 'Mobile'), ('automation', 'Automatisation')], max_length=20, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=60, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=80, help_text='Pourcentage 0-100', verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_photo',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_role',
            field=models.CharField(help_text='ex: COO, RetailTech Paris', max_length=150, verbose_name='fonction'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='entreprise'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.project', verbose_name='projet'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='soumis le'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.CharField(max_length=60, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon_class',
            field=models.CharField(help_text='Classe CSS couleur ex: icon-python', max_length=40, verbose_name='classe CSS'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(max_length=80, verbose_name='titre'),
        ),
    ]
