# Generated by Django 5.1.4 on 2026-05-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_heroslide_siteprofile_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_video_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_video_file',
            field=models.FileField(blank=True, help_text='Vidéo démo uploadée directement (mp4, webm)', upload_to='projects/videos/', verbose_name='fichier vidéo de démo'),
        ),
    ]
