# Generated by Django 5.1.4 on 2026-05-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_demo_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(help_text='Image recommandée: 1600x1000 px minimum, ratio 16:10, cadrage horizontal propre.', upload_to='projects/thumbnails/', verbose_name='miniature'),
        ),
    ]
