# Generated by Django 5.1.4 on 2026-05-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Image recommandee: 1200x1500 px minimum, ratio portrait 4:5, visage bien centre avec espace au-dessus de la tete.', upload_to='profile/', verbose_name='photo de profil'),
        ),
    ]
