# Generated by Django 5.2.11 on 2026-05-01 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_siteprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='', verbose_name='URL WhatsApp'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note'),
        ),
    ]
