# Generated by Django 5.2.11 on 2026-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_rating_validators_and_remove_pii_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='services_section_subtitle',
            field=models.CharField(blank=True, default='Services', max_length=120, verbose_name='sous-titre services'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='services_section_title',
            field=models.CharField(blank=True, default='Ce que je fais', max_length=120, verbose_name='titre services'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='skills_section_subtitle',
            field=models.CharField(blank=True, default='Stack technique', max_length=120, verbose_name='sous-titre competences'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='skills_section_title',
            field=models.CharField(blank=True, default='Compétences', max_length=120, verbose_name='titre competences'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tools_section_subtitle',
            field=models.CharField(blank=True, default='Outils & plateformes', max_length=120, verbose_name='sous-titre outils'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tools_section_title',
            field=models.CharField(blank=True, default='Stack operationnelle', max_length=120, verbose_name='titre outils'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tools_section_desc',
            field=models.TextField(blank=True, default="Des outils robustes pour livrer vite, securiser l'execution et scaler proprement.", verbose_name='description outils'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tools_section_intro',
            field=models.TextField(blank=True, default="Une vision plus visuelle de mon ecosysteme : chaque bloc combine un logo avec les plateformes que j'utilise au quotidien.", verbose_name='intro outils'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='portfolio_section_title',
            field=models.CharField(blank=True, default='Projets & Réalisations', max_length=160, verbose_name='titre portfolio'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='portfolio_section_desc',
            field=models.TextField(blank=True, default='Des projets concrets, orientés résultats et livrables mesurables.', verbose_name='description portfolio'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='testimonials_section_subtitle',
            field=models.CharField(blank=True, default='Témoignages', max_length=120, verbose_name='sous-titre temoignages'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='testimonials_section_title',
            field=models.CharField(blank=True, default='Ce que disent mes clients', max_length=160, verbose_name='titre temoignages'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='contact_section_subtitle',
            field=models.CharField(blank=True, default='Contact', max_length=120, verbose_name='sous-titre contact'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='contact_section_title',
            field=models.CharField(blank=True, default='Travaillons ensemble', max_length=160, verbose_name='titre contact'),
        ),
    ]
