# Generated by Django 5.2.11 on 2026-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_add_home_section_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='cert_section_title',
            field=models.CharField(blank=True, default='Ma Certification Spécialisée en Developpement Logiciel && IA', max_length=180, verbose_name='titre certifications'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='cert_section_desc',
            field=models.TextField(blank=True, default='Mon expertise est prouvée et certifiée par IBM / Coursera.', verbose_name='description certifications'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='cert_section_note',
            field=models.CharField(blank=True, default='Cliquez sur le badge pour vérifier la certification sur Credly.', max_length=180, verbose_name='note certifications'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='primary_certificate_badge',
            field=models.FileField(blank=True, help_text='Image ou PDF du badge (jpg, png, pdf).', upload_to='profile/', verbose_name='badge certification 1'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='secondary_certificate_badge',
            field=models.FileField(blank=True, help_text='Image ou PDF du badge (jpg, png, pdf).', upload_to='profile/', verbose_name='badge certification 2'),
        ),
    ]
