# Generated by Django 5.2.11 on 2026-05-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_add_certification_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='libellé')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL certification')),
                ('badge_file', models.FileField(blank=True, help_text='Image ou PDF du badge (jpg, png, pdf).', upload_to='profile/', verbose_name='badge')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('site_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_badges', to='portfolio.siteprofile', verbose_name='profil du site')),
            ],
            options={
                'verbose_name': 'badge de certification',
                'verbose_name_plural': 'badges de certification',
                'ordering': ['order', 'id'],
            },
        ),
    ]
