# Generated by Django 5.2.11 on 2026-05-02 12:50

from django.db import migrations


def update_contact_title(apps, schema_editor):
    SiteProfile = apps.get_model('portfolio', 'SiteProfile')
    SiteProfile.objects.filter(contact_section_title='Travaillons ensemble').update(
        contact_section_title='Obtenir un devis gratuit'
    )


def reverse_update_contact_title(apps, schema_editor):
    SiteProfile = apps.get_model('portfolio', 'SiteProfile')
    SiteProfile.objects.filter(contact_section_title='Obtenir un devis gratuit').update(
        contact_section_title='Travaillons ensemble'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_add_certification_badge_model'),
    ]

    operations = [
        migrations.RunPython(update_contact_title, reverse_update_contact_title),
    ]
