# Generated by Django 5.1.4 on 2026-05-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_update_contact_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='brand_name',
            field=models.CharField(default='Omar.tech', max_length=120, verbose_name='nom de marque'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='contact_section_title',
            field=models.CharField(blank=True, default='Obtenir un devis gratuit', max_length=160, verbose_name='titre contact'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon_class',
            field=models.CharField(help_text='Couleur hexa ex: #3776ab', max_length=40, verbose_name='classe CSS'),
        ),
    ]
