# Generated by Django 5.2.11 on 2026-05-02 22:43

import django_ckeditor_5.fields
import django.core.validators
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_siteprofile_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationbadge',
            name='badge_file',
            field=models.FileField(blank=True, help_text='Image ou PDF du badge (jpg, png, pdf).', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), portfolio.models.FileSizeValidator(5)], verbose_name='badge'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenge',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Problème client résolu', verbose_name='problème'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_video_file',
            field=models.FileField(blank=True, help_text='Vidéo démo uploadée directement (mp4, webm)', upload_to='projects/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogv', 'ogg']), portfolio.models.FileSizeValidator(50)], verbose_name='fichier vidéo de démo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description complète'),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Résultat mesurable ex: +32% conversion', verbose_name='résultat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Solution apportée', verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(help_text='Image recommandée: 1600x1000 px minimum, ratio 16:10, cadrage horizontal propre.', upload_to='projects/thumbnails/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), portfolio.models.FileSizeValidator(8), portfolio.models._validate_image_content], verbose_name='miniature'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='about_body',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Mon approche est simple : comprendre le problème métier, sécuriser l’architecture, livrer vite et mesurer l’impact. J’accompagne aussi bien des lancements MVP que des plateformes critiques, assistants virtuels et systèmes intelligents connectés au cloud.', verbose_name='texte à propos'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='about_intro',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Développeur full-stack spécialisé en IA, logiciels métier, applications mobiles, cloud AWS et automatisation, je transforme des besoins complexes en produits fiables, scalables et orientés retour sur investissement. Certifié IBM, j’interviens comme partenaire technique pour des entreprises en Afrique francophone, Europe et remote international.', verbose_name='introduction à propos'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='about_photo',
            field=models.ImageField(blank=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), portfolio.models.FileSizeValidator(5), portfolio.models._validate_image_content], verbose_name='photo à propos'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='cert_section_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Mon expertise est prouvée et certifiée par IBM / Coursera.', verbose_name='description certifications'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['pdf']), portfolio.models.FileSizeValidator(10)], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='hero_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Je conçois et mets en production des produits IA, applications métier, stacks cloud AWS et assistants virtuels pour startups, PME et équipes qui veulent livrer plus vite, mieux servir leurs clients et structurer leur croissance en Afrique et à l’international.', verbose_name='description hero'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='portfolio_section_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Des projets concrets, orientés résultats et livrables mesurables.', verbose_name='description portfolio'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='primary_certificate_badge',
            field=models.FileField(blank=True, help_text='Image ou PDF du badge (jpg, png, pdf).', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), portfolio.models.FileSizeValidator(5)], verbose_name='badge certification 1'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Image recommandee: 1200x1500 px minimum, ratio portrait 4:5, visage bien centre avec espace au-dessus de la tete.', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), portfolio.models.FileSizeValidator(5), portfolio.models._validate_image_content], verbose_name='photo de profil'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='secondary_certificate_badge',
            field=models.FileField(blank=True, help_text='Image ou PDF du badge (jpg, png, pdf).', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), portfolio.models.FileSizeValidator(5)], verbose_name='badge certification 2'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='tools_section_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default="Des outils robustes pour livrer vite, securiser l'execution et scaler proprement.", verbose_name='description outils'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='tools_section_intro',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default="Une vision plus visuelle de mon ecosysteme : chaque bloc combine un logo avec les plateformes que j'utilise au quotidien.", verbose_name='intro outils'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_photo',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), portfolio.models.FileSizeValidator(3), portfolio.models._validate_image_content], verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
    ]
