# Generated by Django 5.1.4 on 2026-05-04 16:52

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_certificationbadge_badge_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='image principale'),
        ),
        migrations.AddField(
            model_name='service',
            name='demo_video_file',
            field=models.FileField(blank=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='vidéo démonstration'),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_points',
            field=models.TextField(blank=True, help_text='Un point par ligne pour affichage en liste.', verbose_name='points clés'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='description détaillée'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_image',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='image secondaire'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, verbose_name='résumé'),
        ),
    ]
