# Generated by Django 5.1.4 on 2026-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_project_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='secondary_image',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_photo',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="URL de l'image principale hébergée (ex: Supabase).", verbose_name='URL image principale'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_image_url',
            field=models.URLField(blank=True, help_text="URL de l'image secondaire hébergée (ex: Supabase).", verbose_name='URL image secondaire'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_photo_url',
            field=models.URLField(blank=True, help_text='URL de la photo à propos hébergée (ex: Supabase).', verbose_name='URL photo à propos'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL de la photo de profil hébergée (ex: Supabase).', verbose_name='URL photo de profil'),
        ),
    ]
