# Generated by Django 5.1.4 on 2026-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_service_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='secondary_image_url',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_photo_url',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image principale du service.', upload_to='services/', verbose_name='image principale'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Image secondaire du service.', upload_to='services/', verbose_name='image secondaire'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_photo',
            field=models.ImageField(blank=True, help_text='Image recommandée: 1200x1500 px minimum, ratio portrait 4:5.', upload_to='profile/', verbose_name='photo à propos'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Image recommandée: 1200x1500 px minimum, ratio portrait 4:5, visage bien centré avec espace au-dessus de la tête.', upload_to='profile/', verbose_name='photo de profil'),
        ),
    ]
