# Generated by Django 5.1.4 on 2026-05-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_service_cover_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='secondary_image',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_photo',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_photo',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL publique de la miniature (Supabase).', verbose_name='URL miniature'),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="URL publique de l'image principale (Supabase).", verbose_name='URL image principale'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_image_url',
            field=models.URLField(blank=True, help_text="URL publique de l'image secondaire (Supabase).", verbose_name='URL image secondaire'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_photo_url',
            field=models.URLField(blank=True, help_text='URL publique de la photo à propos (hébergée sur Supabase).', verbose_name='URL photo à propos'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL publique de la photo de profil (hébergée sur Supabase).', verbose_name='URL photo de profil'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_photo_url',
            field=models.URLField(blank=True, help_text='URL publique de la photo auteur (Supabase).', verbose_name='URL photo auteur'),
        ),
    ]
