# Generated by Django 5.1.4 on 2026-05-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_remove_project_thumbnail_remove_service_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='URL publique de la vidéo de démonstration (Supabase).', verbose_name='URL vidéo démo'),
        ),
        migrations.AddField(
            model_name='service',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='URL publique de la vidéo de démonstration (Supabase).', verbose_name='URL vidéo démo'),
        ),
    ]
